---

# SSH keys are stored in /etc/ssh/authorized_keys/$user
# This prevents users without sudo access from changing the keys without
# committing the changes into ansible.

- name: create the /etc/ssh/sshd_config.d directory
  file:
    path: /etc/ssh/sshd_config.d
    state: directory
    mode: 0700

- name: upload sshd configuration
  template:
    src: ssh/sshd_config
    dest: /etc/ssh/sshd_config

  notify: reload-ssh

- name: create authorized keys directory
  file:
    path: /etc/ssh/authorized_keys
    state: directory
    mode: 0755

- name: upload users ssh keys
  copy:
    content: |
      {{ lookup('file', 'ssh-keys/' + item + '.pub') }}
      {{ lookup('file', 'ssh-keys/_master.pub') }}
    dest: "/etc/ssh/authorized_keys/{{ item }}"
    mode: 0444

  notify: reload-ssh

  loop: "{{ unprivileged_users + sudo_users }}"
