[package]
name = "setup-deploy-keys"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[[bin]]
name = "deploy"
path = "src/deploy.rs"

[dependencies]
structopt = "0.2.15"
chrono = "0.4.6"
reqwest = "0.9.16"
serde_json = "1.0.39"
