---

- hosts: dev-desktop
  become: yes
  become_user: root

  roles:

    - role: common
      papertrail_url: "{{ vars_papertrail_url }}"
      collect_metrics_from: "{{ global_collect_metrics_from }}"
      sudo_users: "{{ global_sudo_users + vars_extra_sudo_users }}"
      allow_ssh_extra_groups: dev-desktop-allow-ssh

    - role: datadog.datadog
      vars:
        datadog_api_key: "{{ vars_datadog_api_key }}"
        datadog_site: "datadoghq.com"

        datadog_agent_version: "7.56.2"
        datadog_config:
          tags:
            - "env:{{ vars_environment }}"
            - "service:dev-desktops"
          process_config:
            enabled: "true"

    - role: dev-desktop
